image: golang:1.8

verify:
  image: golang:1.10
  script:
  - make verify

.test_template: &test_definition
  services:
    - name: registry.gitlab.com/gitlab-org/build/cng/gitaly:fix-default-gitaly-config
      command: ["bash", "-c", "rm -rf /srv/gitlab-shell/hooks/* && exec /scripts/process-wrapper"]
      alias: gitaly
  variables:
    GITALY_ADDRESS: "tcp://gitaly:8075"
  script:
  - apt update -qq && apt install -y unzip bzip2
  - go version
  - make test

test using go 1.8:
  <<: *test_definition

test using go 1.9:
  image: golang:1.9
  <<: *test_definition

test using go 1.10:
  image: golang:1.10
  <<: *test_definition

test:release:
  only:
    - tags
  script:
    - git describe --exact-match
