image: golang:1.8

.test_template: &test_definition
  script:
  - apt update -qq && apt install -y unzip bzip2
  - go version
  - make test

test using go 1.8:
  <<: *test_definition

test using go 1.9:
  image: golang:1.9
  <<: *test_definition

test:release:
  only:
    - tags
  script:
    - git describe --exact-match
